


jwt:
  secret: "9cZjXN9uHH0erCgOAdZCsXIAJbeh7Q43eLa/c1a69rU="
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  sql:
    init:
      mode: always
      data-locations: classpath*:sql/data.sql
      schema-locations: classpath*:sql/schema.sql